config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'welcome#main'

  get 'welcome/about'

  get 'welcome/members'

  get 'welcome/about_nsbemon'

  get 'nsbemon/main'

  get 'nsbemon/train'

  patch 'nsbemon/add_amounts'

  post 'user/add_sub_values'

  get 'user/admin_page'

  resources :team

  resources :user do 
    resource :profile
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user

  #Needed so that we can tell Rails 
  #we are changing values in for the
  #records
  include ActiveModel::Dirty

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy
  belongs_to :team 
  has_many :record, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
      if current_user.profile
        nsbemon_main_path
      else
        new_user_profile_path(current_user)
      end
    end 
end

app/controllers/nsbemon_controller.rb
class NsbemonController < ApplicationController
  before_filter :authenticate_user!
  
  def main
    
  end

  def train
    @select = current_user
  end 

  def add_amounts

    temp_record = []
    temp_score  = []

    params.each do |key, value| 
      if (key.to_s[/nsbe_\w+/])
        add_points(value)

        temp_record << key.to_s
        temp_score  << value.to_s
      end
    end

    #Check if the array actually changed
    if !temp_record.empty?
      #Create a record for ADMIN
      new_record = current_user.record.create( checked_boxes: temp_record, 
                                               point_values: temp_score) 
    end

    current_user.level = 10 + (current_user.experience / 50)

    current_user.save

    redirect_to nsbemon_main_path, notice: "Successfully logged points"
  end

  private

  def add_points(point_amount)
    current_user.experience += point_amount.to_i
  end
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  # GET /profiles/new
  def new
    @profile = current_user.create_profile
  end

  # POST /profiles
  def create
    @profile = current_user.profile.new(profile_params)
    if @profile.save
      redirect_to nsbemon_main_path, notice: "Successfully created profile"
    else
      render action: :new
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # PATCH/PUT /profiles/1
  def update
    @profile = current_user.profile

    if @profile.update(profile_params)
      redirect_to nsbemon_main_path, notice: 'Updated user information successfully.'
    else
      render action: :edit
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :graduation_year, :major, :trainer_name, :gpa)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected 

    def after_sign_up_path_for(resource)
      new_user_profile_path(current_user)    
    end

    def after_inactive_sign_up_path_for(resource)
      root_path
    end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  
  # GET /teams
  def index
    @teams = Team.all
  end

  # GET /teams/1
  def show
    @team = Team.find(params[:id])
    @team_trainers = @team.users
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :description)
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :check_privileges!, only: [:admin_page]

  # GET /users
  def index
    @users = User.order("experience DESC").all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @user_profile = @user.profile
  end

  def admin_page
    @users = User.all
  end

  def add_sub_values

    trainer = nil
    points = 0

    params.each do |key, val| 
      if key == "Trainer"
        trainer = User.find(val)
      end

      if key ==  "Points"
        points = val["0"].to_i unless val["0"].empty?
      end
    end

    if ((points != 0) && ((trainer.experience + points) >= 0))
      trainer.experience += points
      trainer.save
      redirect_to user_admin_page_path, notice: "Successfully updated values"
      return 
    end

    redirect_to user_admin_page_path, alert: "Input empty or too negative!"
  end

 private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:level, :experience)
    end

    def check_privileges!
      redirect_to "/", notice: 'You do not have superUser privileges' unless current_user and current_user.try(:admin?)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def main
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nsbemon_helper.rb
module NsbemonHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/team_helper.rb
module TeamHelper
  def exists?(item)
    item == nil ? false : true
  end
end

app/helpers/user_helper.rb
module UserHelper
  def exists?(item)
    item == nil ? false : true
  end

  def experience_for_next_level(level)
    (level - 10) * 50
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NSBEwebSiteRails" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  <body>
    <div class="wrapper">
      <!-- Navigation Bar Section -->
      <div class="navbar navbar-default" role="navigation"> 
        <div class="container">
          <!-- Main Logo -->  
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target=".navbar-collapse">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"> 
              <!-- NSBE logo  --> 
              <%= image_tag("nsbe-logo.jpeg", alt: 'NSBE Logo', width: 115, height: 55) %>
            </a>
          </div> <!-- navbar-header -->
      
          <!-- Navigation Elements --> 
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li> <%= link_to("Home", root_path) %> </li>
              <li class='dropdown'> 
                <a href="#" class='dropdown-toggle' data-toggle='dropdown' style='background-color: rgba(0,0,0,0);'>
                  NSBEmon
                  <span class='caret'></span>
                </a>
                <ul class='dropdown-menu' role='menu' style='background-color: rgba(70, 140, 215, .90);'> 
                  <li>
                    <%= link_to('Training Grounds', nsbemon_main_path) %> 
                  </li>
                  <li>
                    <% if current_user.try(:admin?) %>
                      <%= link_to('Admin Page', user_admin_page_path) %> 
                    <% end %>
                  </li>
                </ul>
            </ul> 
            <p class="navbar-text pull-right">
                  <% if user_signed_in? %>
                    Logged in as <strong><%= current_user.email %></strong>.
                    <%= link_to 'Edit_Profile', edit_user_registration_path, style:'color: #FFFFFF;' %> |
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete , style:'color: #FFFFFF;' %>
                  <% else %>
                    <%= link_to "Sign up", new_user_registration_path, style:'color: #FFFFFF;' %> |
                    <%= link_to "Login", new_user_session_path, style:'color: #FFFFFF;' %>
                  <% end %>
                </p>
          </div> <!-- navbar-collapse collapse -->
        </div> <!-- container -->
      </div> <!-- navbar navbar-inverse navbar-static-top -->

      <% if notice %>
        <p class="alert alert-success "><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

      <!-- <div class="push"></div> -->
    </div>

    <div class="footer">
      <div class="container">
        <p class="muted credit">
          NSBE at UCLA with Love &#9829
        </p>
      </div>
    </div>

  </body>
</html>

app/views/nsbemon/_begin.html.erb
<div class="row"> 
      <div class="col-lg-12">
        <%= yield %>
      </div>
</div> 

app/views/nsbemon/main.html.erb
<!-- Carousel Design from Bootstrap Examples -->
<div id="myCarousel" class="carousel slide" data-interval="7500" data-ride="carousel">
    <div class="carousel-inner">
        <div class="item active">
            <%= image_tag("red.jpg", alt: 'All Pokemon') %>
        </div> <!-- item active -->
    </div> <!-- carousel-inner -->
  
</div> <!-- carousel slide --> 

<div class="container marketing">
    <div class="row featurette"> <!-- FIRST ROW --> 
        
        <div class="col-md-5">
            <%= image_tag("pokemon-starters.png", class: "featurette-image img-responsive") %>
        </div> <!-- col-md-5 -->

        <div class="col-md-7" style="margin-bottom: 25px; ">
            <h2 class="featurette-heading"> Train Your Pokemon! </h2>
            <p class="lead">
                Better log all those hard hours of training to be the best!
            </p> 
            <%= link_to("Train", nsbemon_train_path, class: "btn btn-info") %>   
        </div> <!-- col-md-7 -->

    </div> <!-- row featurette --> 
    
    <hr class="featurette-divider">

    <div class="row featurette"> <!-- SECOND ROW -->
    
        <div class="col-md-7" style="margin-bottom: 25px; ">
            <h2 class="featurette-heading"> Update your Profile! </h2>
            <p class="lead">
                Let us know who you are!
            </p> 

            <% if exists? current_user.profile %>
                <%= link_to "Update Profile", edit_user_profile_path(current_user) , class: "btn btn-info" %>
            <% else %>
                <%= link_to "New Profile", new_user_profile_path(current_user), class: "btn btn-info" %>   
            <% end %>
        </div> <!-- col-md-7 -->

        <div class="col-md-5">
            <%= image_tag("BlankTrainerCard.png", class: "featurette-image img-responsive") %>
        </div> <!-- col-md-5 -->

    </div> <!-- row featurette --> 
    
    <hr class="featurette-divider">


    <div class="row featurette"> <!-- THIRD ROW -->
        
        <div class="col-md-5">
            <%= image_tag("teams.jpg", class: 'featurette-image img-responsive') %>
        </div> <!-- col-md-5 -->

        <div class="col-md-7">
            <h2 class="featurette-heading"> Meet all the NSBEmon Teams! </h2>
            <p class="lead">
                See who has the most badass team in the 
                neighborhood.
            </p>    
            <%= link_to("Teams", team_index_path, class: "btn btn-info") %>
        </div> <!-- col-md-7 -->
        
    </div> <!-- row featurette --> 
    
    <!-- Put a divider between the two icons --> 
    <hr class="featurette-divider"> 
        
    <div class="row featurette"> <!-- FOURTH ROW -->
    
        <div class="col-md-7" style="margin-bottom: 25px; ">
            <h2 class="featurette-heading"> Meet all the NSBEmon Trainers! </h2>
            <p class="lead">
                Come look at all the stories of these amazing and hard working 
                individuals!
            </p> 
            <%= link_to("Trainers", user_index_path, class: "btn btn-info") %>   
        </div> <!-- col-md-7 -->

        <div class="col-md-5">
            <%= image_tag("trainers.jpg", class: "featurette-image img-responsive") %>
        </div> <!-- col-md-5 -->

    </div> <!-- row featurette --> 
    
    <hr class="featurette-divider">
        
</div> <!-- container marketing --> 

app/views/nsbemon/train.html.erb
<div class='border-form-div'>
    <%= form_tag({controller: "nsbemon", action: "add_amounts"}, method: "patch" ) do %>
        
        <%= render :layout => "begin" do %>
          <h1>NSBEmon Training</h1>
        <% end %>

        <%= render :layout => "begin" do %>
          <h3> Gym: In Class </h3>
        <% end %>

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_in_class_1', '5' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Sat in the front row" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_in_class_2', '10' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Asked a question in class" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_in_class_3', '15' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Talked to the professor during the break" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_in_class_4', '200' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Did not miss a discussion during the quarter" %>
            </div>
        </div> 
        
        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_in_class_5', '500' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Did not miss a lecture during the quarter" %>
            </div>
        </div> 

        <%= render :layout => "begin" do %>
          <h3> Gym: The Professor </h3>
        <% end %>

        <div class="row"> 
            <div class="col-lg-3">
                 <%= check_box_tag 'nsbe_professor_1', '5' %>
            </div>
            <div class="col-lg-9">
                 <%= label_tag "Emailed TA or Professor with question" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_professor_2', '10' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Attended Office Hour" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_professor_3', '15' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Professor knows my name" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_professor_4', '20' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Submitted paper for regrade and gained points" %>
            </div>
        </div>    


        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_professor_5', '25' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Set up appointment with Professor" %>
            </div>
        </div>    

        

        <%= render :layout => "begin" do %>
          <h3> Gym: Study Habits </h3>
        <% end %>

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_study_1', '15' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Completed homework at least two days in advance" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_study_2', '15' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Reviewed Notes before and after class" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_study_3', '15' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Read textbook" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_study_4', '20' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Did extra problems apart from homework" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_study_5', '20' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Taught another person the a subject" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_study_6', '30' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Planned a study group" %>
            </div>
        </div> 


        <%= render :layout => "begin" do %>
            <h3> Gym: Personal Best </h3>
        <% end %> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_personal_1', '30' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Improved quiz score" %>
            </div>
        </div> 
        
        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_personal_2', '50' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Improved midterm score" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_personal_3', '75' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Did better than my peers in a midterm" %>
            </div>
        </div> 

       
        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_personal_4', '100' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Improved GPA" %>
            </div>
        </div> 

        <div class="row"> 
            <div class="col-lg-3">
                <%= check_box_tag 'nsbe_personal_5', '500' %>
            </div>
            <div class="col-lg-9">
                <%= label_tag "Reached goal GPA" %>
            </div>
        </div> 

        <div class="row">
          <div class="col-lg-12">
            <%= submit_tag "Log Training", class: 'btn btn-primary'%>
          </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <%= link_to 'Back', nsbemon_main_path %>
            </div>
        </div>

    <% end %>

</div>

app/views/profiles/_form.html.erb
<%= form_for(@profile, url: user_profile_path(@profile), html: { method: :put}) do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>

  <%= f.label :trainer_name %>
  <%= f.text_field :trainer_name %><br>

  <%= f.label :gpa %><br>
  <%= f.number_field :gpa, :step => 0.01, :max => 4.00, :min => 0.00 %><br><br>

  <%= f.label :graduation_year %><br>
  <%= f.select :graduation_year, 
    options_for_select(['2015', 
    '2016',
    '2017', 
    '2018', 
    '2019',
    '2020', 
    '2021'])
    %>
    <br>
    <br>

  <%= f.label :major %><br>
  <%= f.select :major, options_for_select(['Computer Science', 
    'Electrical Engineering',
    'Mechanical Engineering', 
    'Chemical Engineering', 
    'Biomedical Engineering',
    'Civil Engineering', 
    'Aerospace Engineering',
    'Other']) %> 
    <br>
    <br>


  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/profiles/edit.html.erb
<div class='border-form-div'>
  
  <h1>Edit Profile</h1>

  <%= render 'form' %>

  <%= link_to 'Back', nsbemon_main_path %>
</div>

app/views/profiles/new.html.erb
<div class='border-form-div'>
  
  <h1>New Profile</h1>

  <%= render 'form' %>

  <%= link_to 'Back', nsbemon_main_path %>
</div>

app/views/team/_team.html.erb
<div class="row" style="margin-top: 15px; ">
  <div class="container">
    <div class="col-lg-6">
      <% if team.name == "Team Rocket" %>
        <%= image_tag("teamrocket.png", class: 'featurette-image img-responsive pictureWrapper') %>
      <% elsif team.name == "Team Magma" %>
        <%= image_tag("teammagma.png", class: 'featurette-image img-responsive pictureWrapper') %>
      <% elsif team.name == "Team Aqua" %>
        <%= image_tag("teamaqua.png", class: 'featurette-image img-responsive pictureWrapper') %>
      <% elsif team.name == "The Elite Four" %>
        <%= image_tag("elitefour.jpg", class: 'featurette-image img-responsive pictureWrapper') %>
      <% else %>
        <%= image_tag("epicredteam.jpg", class: 'featurette-image img-responsive pictureWrapper') %>
      <% end %>
    </div>
    <div class="col-lg-6">
      <h1> <%= link_to team.name, team %> </h1>
      <h2> <%= team.description %> </h2>
    </div>

  </div>
</div>

<hr>

app/views/team/index.html.erb
<div class="container">  
  <div class="row">
    <div class="col-lg-12">
      <%= image_tag("teams.jpg", class: 'featurette-image img-responsive') %>
    </div>
  </div>
</div>

<hr>

<% if exists? @teams %>
  <div class="team">
    <%= render partial: "team", collection: @teams %>
  </div>
<% end %>

app/views/team/show.html.erb
<%= render partial: "team", object: @team %>

<%= render partial: "user/user", collection: @team_trainers %>

app/views/user/_user.html.erb
<% if user.confirmed? %>
  <% if exists? user.profile %>
    <div class="container">
      <div class="row">

        <div class="panel panel-success">
          <div class="panel-heading">
            <div class="container">
              <div class="row">
                <div class="col-xs-8 col-sm-9 col-md-10">
                  <% if user.profile.first_name %>
                    <h5> Trainer <%= user.profile.first_name %> <%= user.profile.last_name %></h5>
                  <% else %>
                    <h5> Trainer <%= user.email %> </h5>
                  <% end %>
                </div>
                <div class="col-xs-4 col-sm-3 col-md-2">
                    <% if user.profile.first_name %>
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#<%=user.profile.first_name%>">
                        Trainer Profile
                      </button>
                    <% else %>
                      <button type="button" class="btn btn-danger">
                        No Profile
                      </button>
                    <% end %>
                </div>

              </div>

            </div>
          </div>
          <div class="panel-body">
            <div class="container">
              <div class="row">
                <div class="col-xs-11">
                  <h5> Next Level: <%= user.level + 1 %></h5>
                  <div class="progress">
                    <div class="progress-bar progress-bar-success progress-bar-striped active"
                         role="progressbar"
                         aria-valuenow="<%= user.experience %>"
                         aria-valuemin="<%= experience_for_next_level user.level %>"
                         aria-valuemax="<%= experience_for_next_level (user.level + 1)%>"
                         style="width: <%=user.experience - experience_for_next_level(user.level)%>%">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="<%=user.profile.first_name%>" tabindex="-1" role="dialog" aria-labelledby="<%=user.profile.first_name%>">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Trainer Profile</h4>
          </div>
          <div class="modal-body">
              <div class="row">
                  <div class="col-sm-4 hidden-xs">
                    <%= image_tag("poketrainers.png", class: 'featurette-image img-responsive pictureWrapper') %>
                  </div>
                  <div class="col-sm-8">

                    <h3> <%= user.profile.first_name %> <%= user.profile.last_name %> </h3>
                    <h3>
                      <i class="fa fa-flag"></i>
                      <%= user.level %>
                    </h3>
                    <h3>
                      <i class="fa fa-flash"></i>
                      <%= user.experience %>
                    </h3>
                    <h3>
                      <i class="fa fa-book"></i>
                      <%= user.profile.major %>
                    </h3>
                    <h3>
                      <i class="fa fa-graduation-cap"></i>
                      <%= user.profile.graduation_year %>
                    </h3>
                  </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <hr>
  <% end %>
<% end %>

app/views/user/admin_page.html.erb
<%= form_tag(controller: "user", action: "add_sub_values") do %>
  <%= select_tag 'Trainer', options_from_collection_for_select(@users, 'id', 'email') %>

  <%= number_field("Points", value = 0, in: -5000..5000, step: 10 )%>

  <%= submit_tag("Add amount") %>

<% end %>

<% @users.each do |user| %>
  <div class="table-responsive">
    <table class="table">
        <tr>
          <td> <b>User email: <%= user.email %></b> </td>
          <td> <b>User experience: <%= user.experience %></b> </td>
          <td> <b>User First Name: <%= user.profile.first_name %></b> </td>
        </tr>
    </table>
  </div>
 
  <div class="table-responsive" style="overflow-x:auto;">
    <table class="table table-striped">
      <% user.record[0...5].reverse.each do |r| %>
        <tr>
          <% r.checked_boxes.zip(r.point_values).each do |box, value| %>
              <td> <%= box[5, box.length] + " : " + value + " pts" %> </td>
          <% end %>
          <td> <b><%= r.created_at.localtime.strftime("%e %b %Y %H:%M:%S") %></b> </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/user/index.html.erb
<div class="container">  
  <div class="row">
    <div class="col-lg-12">
      <%= image_tag("trainers.jpg", class: 'featurette-image img-responsive') %>
    </div>
  </div>
</div>

<hr>

<% if exists? @users %>
  <div class="user">
    <%= render partial: "user", collection: @users %>
  </div>
<% end %>